### ISSUE TITLE
Error generating frozen_mpy.c

### ISSUE THREAD

**Issue by odudex** [selfcustody/krux#107]
After recent changes I'm not able to build for devices different from m5stickv (maix bit and amigo). I'm getting this error when change the device:
ex: ./krux build maixpy_amigo_ips 1.0.0

> [ 21%] Generating frozen_mpy.c
> usage: mpy-tool.py [-h] [-d] [-f] [-q QSTR_HEADER]
>                    [-mlongint-impl {none,longlong,mpz}] [-mmpz-dig-size N]
>                    files [files ...]
> mpy-tool.py: error: the following arguments are required: files

**Comment by jreesun** [comment]
Fixed by https://github.com/selfcustody/krux/commit/cc4e45157d799e529b8a251e7a43f4be7b96565b, thanks for letting me know!

By the way, you don't need to pass a version string to the `build` command anymore. It now pulls that information from the `version` key in `pyproject.toml` and applies it to the `metadata.py` file and the build so they always agree with each other
