### ISSUE TITLE
Blue Wallet will create a legacy wallet from Krux's xpub

### ISSUE THREAD

**Issue by odudex** [selfcustody/krux#124]
To further investigate: People may fall into an issue when using Krux with Blue Wallet. If a xpub is imported Blue wallet will create a legacy wallet with /84 derivation. Than Krux won't be able to use or sign transactions for this wallet, as it is incompatible with legacy.
(As I remember) It will fail to importing a transaction in:
```
# get policy of the input
            try:
                inp_policy = get_policy(inp, inp.witness_utxo.script_pubkey, xpubs)
            except:
                raise ValueError("Unable to get policy")
```

**Comment by jreesun** [comment]
This is only a problem if they export the first xpub QR code to BlueWallet instead of the second zpub QR code, right?

If that's the case, I think this could be added to the FAQ on the site to explain the issue. 

Also, the instructions on the site for BlueWallet do say:
> On your Krux, navigate to the Extended Public Key option under the main menu and make sure to show the second, zpub QR code to BlueWallet.

https://selfcustody.github.io/krux/getting-started/using-a-single-key-wallet/#create-the-wallet
