### ISSUE TITLE
CMake Error when building the firmware 

### ISSUE THREAD

**Issue by bavarianledger** [selfcustody/krux#19]
Thanks for this great project.

I am trying to build the firmware on a freshly installed Ubuntu system.
But CMake throws an error in Step 15/15 after `vagrant ssh -c 'cd /vagrant; ./krux build-firmware'`:
```
-- builtin py dir: /src/MaixPy/projects/maixpy_m5stickv/builtin_py
-- [register component: micropython ], path:/src/MaixPy/components/micropython
CMake Error at /src/MaixPy/tools/cmake/compile.cmake:82 (message):
  Can not find port/src/speech/maix_asr/libmaix_asr.a or
  /src/MaixPy/components/micropython/port/src/speech/maix_asr/libmaix_asr.a
Call Stack (most recent call first):
  /src/MaixPy/components/micropython/CMakeLists.txt:564 (register_component)
```

Any idea what I'm missing here?

**Comment by jreesun** [comment]
@bavarianledger Can you pull down the latest code and give that a try?

**Comment by bavarianledger** [comment]
> @bavarianledger Can you pull down the latest code and give that a try?

Yes, the firmware is now building.
Thanks for the quick fix!

But I'm stuck now on flashing the firmware:
```
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
find: ‘/sys/kernel/debug’: Permission denied
find: ‘/sys/fs/pstore’: Permission denied
find: ‘/sys/fs/fuse/connections/47’: Permission denied
Failed to find device via USB. Is it connected and powered on?
Connection to 127.0.0.1 closed.
```
Are you running vagrant as `root`?

**Comment by jreesun** [comment]
No, that shouldn't be necessary to run it as root. Those `Permission denied` messages can be ignored, they aren't causing the issue.

Make sure to:
1) Plug in the M5StickV via USB before anything else,
2) Turn on the M5StickV (press the lower left-side button, or hold it down), then
3) Run `vagrant reload && vagrant ssh -c 'cd /vagrant; ./krux flash-firmware'`

The device needs to be on and plugged in prior to vagrant being started (or reloaded), otherwise it won't pass the serial connection through and will lead to that error. Sometimes it's finicky and you need to turn the device fully off (or resetting) before plugging it in and turning it on.

Does that resolve the problem, or is it still happening even after doing those steps?

If it's still a problem, can you run`vboxmanage list usbhost`? You should see an entry with `Product:            M5Stack Intf` if VirtualBox is able to detect the device on your host machine.

**Comment by bavarianledger** [comment]
Thanks.
Flashing is working now.
The issue was that the user running VirtualBox/Vagrant wasn't a member of the vboxusers group and therefore couldn't access the USB devices.

I created a little [PR](https://github.com/jreesun/krux/pull/20) to prevent other from the same mistake - maybe that's useful.
