### ISSUE TITLE
USB no longer being recognized by the computer

### ISSUE THREAD

**Issue by edbfraga** [selfcustody/krux#254]
I'm a newbie.

Why my MaixAmigo is no longer being recognized by my computer?
I'd like flash another firmware for tests.

**Comment by tadeubas** [comment]
Are you using the correct port on amigo? See this: https://selfcustody.github.io/krux/faq/#why-isnt-my-amigo-device-being-recognized-when-connected-to-the-computer-usb

Also, try another port on your PC and even another USB cable

**Comment by edbfraga** [comment]
I already install Krux firmware, after that my USB plug doesn’t recognize my MaixAmigo as a device.

**Comment by edbfraga** [comment]
I already install Krux firmware, after that my USB plug doesn’t recognize my MaixAmigo as a device.

**Comment by edbfraga** [comment]
I already install Krux firmware, after that my USB plug doesn’t recognize my MaixAmigo as a device.

**Comment by odudex** [comment]
Please give us more details, like, what's you OS? Is your Krux working? How to you check if the computer is detecting?

**Comment by edbfraga** [comment]
1. I’m using Windows 10.
2. My Krux is working fine. 
3. I opened the Device Manager.

**Comment by edbfraga** [comment]
I already try with three different cable.

**Comment by edbfraga** [comment]
I tried again. And now this is working.

**Comment by jreesun** [comment]
Did you build the firmware from source inside a Vagrant VM and flash that way @edbfraga ? 

If so, your host computer won't recognize any USB connections from that device while the VM is turned on since VirtualBox "steals" the USB connection to pass it through to the VM guest. You can only talk to the device via the VM while it's on.

You can workaround this by running `vagrant halt` to stop the VM thus freeing up the USB port, or manually shut down the VM in VirtualBox. A full restart of your computer would also do the trick.

That's my best guess for what you experienced and my recommendation if you experience any future problems.
