### ISSUE TITLE
MaixPy should be a submodule

### ISSUE THREAD

**Issue by Giszmo** [selfcustody/krux#78]
Copying code in makes code review hard as now the reviewer also has check where that copied code came from and if it was modified. #39 sounds like this issue might be resolved by removal of the code but anyway, for a Bitcoin wallet code auditability is key.

**Comment by jreesun** [comment]
The changes made to MaixPy are extensive enough (and specific to Krux, such as memory wiping and QR code generation) that in order to do a proper audit, you do need to review the firmware code regardless. 

I think making it a submodule eventually would be worthwhile (if/when Krux is more platform-agnostic), but for now since the firmware code is Krux-specific there isn't much reason to break it out yet. I'll leave this issue open though since it makes sense to do that in the future.

**Comment by jreesun** [comment]
Okay, I see. I can certainly try to do that to make auditing easier 👍

**Comment by jreesun** [comment]
@Giszmo Hey, I just wanted to give you notice that I'm planning to put out the first official release (v1.0.0) of Krux this week!
